### ISSUE TITLE
zcashd error on startup

### ISSUE THREAD

**Issue by fangs87** [bitcoinz-pod/bitcoinz-wallet#27]
[main] [Wed Jan 24 21:55:23 EST 2018] [INFO] zcashd is not runing at the moment or has not started/synchronized 100% - showing splash...
[main] [Wed Jan 24 21:55:23 EST 2018] [INFO] Splash: checking if zcashd is already running...
[main] [Wed Jan 24 21:55:24 EST 2018] [INFO] Splash: zcashd will be started...
[main] [Wed Jan 24 21:55:39 EST 2018] [ERROR] Unexpected error:
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
        at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
        at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
        at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:591)

**Comment by fangs87** [comment]
I see this in the debug.log

2018-01-25 03:22:02 scheduler thread start
2018-01-25 03:22:02 Loaded verifying key in 0.001998s seconds.
2018-01-25 03:22:02 Binding RPC on address ::1 port 1979 failed.
2018-01-25 03:22:02 Binding RPC on address 127.0.0.1 port 1979 failed.
2018-01-25 03:22:02 Unable to bind any endpoint for RPC server
2018-01-25 03:22:02 Error: Unable to start HTTP server. See debug log for details.
2018-01-25 03:22:02 Shutdown: In progress...
2018-01-25 03:22:02 scheduler thread interrupt
2018-01-25 03:22:02 StopRPC: waiting for async rpc workers to stop
2018-01-25 03:22:02 StopNode()
2018-01-25 03:22:02 Shutdown: done

**Comment by fangs87** [comment]
Seems to be my antivirus was blocking it, odd because it loaded fine this morning, ,synced everything and had no issues. but this evening it wouldn't load. no matter what rules or allow access I added to it.
